name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install openjdk
      run: |
        sudo apt-get install -y openjdk-8-jdk

    - name: Check out
      uses: actions/checkout@v1

    - name: Run gradle test
      run: |
        cd backend
        ./gradlew test
